// Code generated by mockery v2.23.2. DO NOT EDIT.

package loggermocks

import mock "github.com/stretchr/testify/mock"

// LoggerInterface is an autogenerated mock type for the LoggerInterface type
type LoggerInterface struct {
	mock.Mock
}

// HandleLog provides a mock function with given fields: _a0, _a1
func (_m *LoggerInterface) HandleLog(_a0 string, _a1 bool) {
	_m.Called(_a0, _a1)
}

type mockConstructorTestingTNewLoggerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewLoggerInterface creates a new instance of LoggerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLoggerInterface(t mockConstructorTestingTNewLoggerInterface) *LoggerInterface {
	mock := &LoggerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
